/**
 * PrognosisMeta - Export & Report Generation Module
 * Generates publication-ready reports and reproducible code
 */

const ExportModule = (function() {
    'use strict';

    function escapeHtml(str) {
        if (str == null) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    // ============================================
    // Report Templates
    // ============================================

    /**
     * Generate HTML report
     */
    function generateHTMLReport(analysisData, options = {}) {
        const {
            title = 'Meta-Analysis Report',
            author = '',
            date = new Date().toLocaleDateString(),
            includeSummary = true,
            includeForest = true,
            includeHeterogeneity = true,
            includeFunnel = true,
            includeBias = true,
            includeSubgroup = false,
            includeMetareg = false,
            includeSensitivity = false
        } = options;

        const { data, results, settings, plots } = analysisData;

        let html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(title)}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 12pt;
            line-height: 1.6;
            max-width: 8.5in;
            margin: 0 auto;
            padding: 1in;
            background: white;
        }
        h1 { font-size: 18pt; margin-bottom: 0.5em; text-align: center; }
        h2 { font-size: 14pt; margin: 1.5em 0 0.5em; border-bottom: 1px solid #333; padding-bottom: 0.25em; }
        h3 { font-size: 12pt; margin: 1em 0 0.5em; }
        .meta-info { text-align: center; color: #666; margin-bottom: 2em; }
        table { width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 10pt; }
        th, td { padding: 0.5em; text-align: left; border: 1px solid #ddd; }
        th { background: #f5f5f5; font-weight: bold; }
        .result-box {
            background: #f9f9f9;
            padding: 1em;
            border-left: 4px solid #2563eb;
            margin: 1em 0;
        }
        .result-value { font-size: 14pt; font-weight: bold; color: #2563eb; }
        .ci { color: #666; }
        .figure { text-align: center; margin: 1.5em 0; page-break-inside: avoid; }
        .figure img { max-width: 100%; height: auto; }
        .figure-caption { font-style: italic; color: #666; margin-top: 0.5em; }
        .interpretation { font-style: italic; padding: 0.5em; background: #e8f4fd; border-radius: 4px; }
        .footer { margin-top: 2em; padding-top: 1em; border-top: 1px solid #ddd; font-size: 10pt; color: #666; }
        @media print {
            body { padding: 0.5in; }
            .page-break { page-break-after: always; }
        }
    </style>
</head>
<body>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta-info">
        ${author ? `<p>Author: ${escapeHtml(author)}</p>` : ''}
        <p>Date: ${escapeHtml(date)}</p>
        <p>Generated by PrognosisMeta</p>
    </div>
`;

        // Summary section
        if (includeSummary && results) {
            html += `
    <h2>Summary</h2>
    <div class="result-box">
        <p><strong>Analysis Type:</strong> ${settings.analysisType === 'prognostic' ? 'Prognostic Factor' : 'Prediction Model'} Meta-Analysis</p>
        <p><strong>Effect Measure:</strong> ${settings.effectMeasure}</p>
        <p><strong>Number of Studies:</strong> ${data.length}</p>
        <p><strong>Method:</strong> ${results.method}</p>
    </div>

    <h3>Pooled Estimate</h3>
    <div class="result-box">
        <p class="result-value">${formatEffect(results.effect, settings)} ${formatCI(results.ci, settings)}</p>
        <p>z = ${results.zValue?.toFixed(2) || results.tValue?.toFixed(2)}, p ${formatPValue(results.pValue)}</p>
        ${results.predictionInterval ? `<p>95% Prediction Interval: ${formatCI(results.predictionInterval, settings)}</p>` : ''}
    </div>
`;
        }

        // Heterogeneity section
        if (includeHeterogeneity && results) {
            html += `
    <h2>Heterogeneity Assessment</h2>
    <table>
        <tr><th>Statistic</th><th>Value</th><th>Interpretation</th></tr>
        <tr>
            <td>Q-statistic</td>
            <td>${results.Q?.toFixed(2)} (df = ${results.df}, p ${formatPValue(results.pHet)})</td>
            <td>${results.pHet !== undefined && results.pHet < 0.1 ? 'Significant heterogeneity detected' : 'No significant heterogeneity'}</td>
        </tr>
        <tr>
            <td>I² (inconsistency)</td>
            <td>${results.I2?.toFixed(1)}% [${results.I2Lower?.toFixed(1)}%, ${results.I2Upper?.toFixed(1)}%]</td>
            <td>${interpretI2(results.I2)}</td>
        </tr>
        <tr>
            <td>τ² (between-study variance)</td>
            <td>${results.tau2?.toFixed(4)} [${results.tau2Lower?.toFixed(4)}, ${results.tau2Upper?.toFixed(4)}]</td>
            <td></td>
        </tr>
        <tr>
            <td>τ (SD)</td>
            <td>${results.tau?.toFixed(4)}</td>
            <td></td>
        </tr>
        <tr>
            <td>H²</td>
            <td>${results.H2?.toFixed(2)}</td>
            <td></td>
        </tr>
    </table>
`;
        }

        // Forest plot
        if (includeForest && plots?.forest) {
            html += `
    <h2>Forest Plot</h2>
    <div class="figure">
        <img src="${plots.forest}" alt="Forest Plot">
        <p class="figure-caption">Figure 1. Forest plot showing individual study effects and pooled estimate.</p>
    </div>
`;
        }

        // Study weights table
        if (data && results?.weights) {
            html += `
    <h2>Study Details</h2>
    <table>
        <tr>
            <th>Study</th>
            <th>N</th>
            <th>Effect</th>
            <th>95% CI</th>
            <th>Weight (%)</th>
        </tr>
`;
            data.forEach((study, i) => {
                html += `
        <tr>
            <td>${escapeHtml(study.study)}</td>
            <td>${study.n || '--'}</td>
            <td>${formatEffect(study.effect, settings)}</td>
            <td>${formatCI({
                lower: study.effect - 1.96 * study.se,
                upper: study.effect + 1.96 * study.se
            }, settings)}</td>
            <td>${results.weights[i]?.toFixed(1) || '--'}</td>
        </tr>
`;
            });
            html += `    </table>`;
        }

        // Publication bias
        if (includeBias && analysisData.biasTests) {
            html += `
    <h2>Publication Bias Assessment</h2>
`;
            if (plots?.funnel) {
                html += `
    <div class="figure">
        <img src="${plots.funnel}" alt="Funnel Plot">
        <p class="figure-caption">Figure 2. Funnel plot for visual assessment of publication bias.</p>
    </div>
`;
            }

            const bias = analysisData.biasTests;
            html += `
    <h3>Statistical Tests</h3>
    <table>
        <tr><th>Test</th><th>Statistic</th><th>p-value</th><th>Interpretation</th></tr>
`;
            if (bias.egger) {
                html += `
        <tr>
            <td>Egger's regression</td>
            <td>Intercept = ${bias.egger.intercept?.toFixed(3)}, t = ${bias.egger.tValue?.toFixed(2)}</td>
            <td>${formatPValue(bias.egger.pValue)}</td>
            <td>${bias.egger.interpretation}</td>
        </tr>
`;
            }
            if (bias.begg) {
                html += `
        <tr>
            <td>Begg's rank correlation</td>
            <td>τ = ${bias.begg.tau?.toFixed(3)}, z = ${bias.begg.z?.toFixed(2)}</td>
            <td>${formatPValue(bias.begg.pValue)}</td>
            <td>${bias.begg.interpretation}</td>
        </tr>
`;
            }
            if (bias.trimFill) {
                html += `
        <tr>
            <td>Trim and Fill</td>
            <td>Missing studies: ${bias.trimFill.k0}</td>
            <td>--</td>
            <td>Adjusted effect: ${formatEffect(bias.trimFill.adjustedEffect, settings)}</td>
        </tr>
`;
            }
            html += `    </table>`;
        }

        // Subgroup analysis
        if (includeSubgroup && analysisData.subgroups) {
            html += `
    <h2>Subgroup Analysis</h2>
    <table>
        <tr><th>Subgroup</th><th>k</th><th>Effect</th><th>95% CI</th><th>I²</th><th>p</th></tr>
`;
            analysisData.subgroups.subgroups.forEach(sub => {
                html += `
        <tr>
            <td>${escapeHtml(sub.group)}</td>
            <td>${sub.k}</td>
            <td>${formatEffect(sub.effect, settings)}</td>
            <td>${formatCI(sub.ci, settings)}</td>
            <td>${sub.I2?.toFixed(1)}%</td>
            <td>${formatPValue(sub.pValue)}</td>
        </tr>
`;
            });
            html += `
    </table>
    <p class="interpretation">Test for subgroup differences: Q = ${analysisData.subgroups.QBetween?.toFixed(2)},
       df = ${analysisData.subgroups.dfBetween}, p ${formatPValue(analysisData.subgroups.pBetween)}</p>
`;
        }

        // Meta-regression
        if (includeMetareg && analysisData.metaRegression) {
            const mr = analysisData.metaRegression;
            html += `
    <h2>Meta-Regression</h2>
    <table>
        <tr><th>Coefficient</th><th>Estimate</th><th>SE</th><th>95% CI</th><th>z/t</th><th>p</th></tr>
`;
            mr.coefficients.forEach((coef, i) => {
                html += `
        <tr>
            <td>${i === 0 ? 'Intercept' : `Moderator ${i}`}</td>
            <td>${coef.estimate?.toFixed(4)}</td>
            <td>${coef.se?.toFixed(4)}</td>
            <td>[${coef.ci.lower?.toFixed(4)}, ${coef.ci.upper?.toFixed(4)}]</td>
            <td>${coef.statistic?.toFixed(2)}</td>
            <td>${formatPValue(coef.pValue)}</td>
        </tr>
`;
            });
            html += `
    </table>
    <p>Residual τ² = ${mr.tau2?.toFixed(4)}, I² (residual) = ${mr.I2Residual?.toFixed(1)}%, R² = ${mr.R2 !== undefined ? (mr.R2 * 100).toFixed(1) : '--'}%</p>
    <p>Test of Moderators: Q_M = ${mr.QM?.toFixed(2)}, df = ${mr.dfM}, p ${formatPValue(mr.pQM)}</p>
`;
        }

        // Sensitivity analysis
        if (includeSensitivity && analysisData.sensitivity) {
            html += `
    <h2>Sensitivity Analysis</h2>
    <h3>Leave-One-Out Analysis</h3>
    <table>
        <tr><th>Excluded</th><th>Effect</th><th>95% CI</th><th>I²</th></tr>
`;
            analysisData.sensitivity.results.forEach(row => {
                html += `
        <tr>
            <td>${escapeHtml(row.excluded)}</td>
            <td>${formatEffect(row.effect, settings)}</td>
            <td>${formatCI(row.ci, settings)}</td>
            <td>${row.I2?.toFixed(1)}%</td>
        </tr>
`;
            });
            html += `
        <tr style="font-weight: bold;">
            <td>Overall</td>
            <td>${formatEffect(analysisData.sensitivity.overall.effect, settings)}</td>
            <td>${formatCI(analysisData.sensitivity.overall.ci, settings)}</td>
            <td>${analysisData.sensitivity.overall.I2?.toFixed(1)}%</td>
        </tr>
    </table>
`;
        }

        // Footer
        html += `
    <div class="footer">
        <p>This report was generated by PrognosisMeta - Prognostic Factor & Prediction Model Meta-Analysis.</p>
        <p>Statistical methods: ${results.method}</p>
        <p>All calculations performed using validated algorithms.</p>
    </div>
</body>
</html>
`;

        return html;
    }

    // ============================================
    // Code Generation
    // ============================================

    /**
     * Generate R code for metafor package
     */
    function generateRCode(data, settings, results) {
        const { analysisType, effectMeasure, tau2Method, hksjAdjustment } = settings;

        let code = `# PrognosisMeta - Generated R Code
# Meta-analysis using metafor package
# Generated: ${new Date().toISOString()}

# Install required packages if needed
# install.packages("metafor")

library(metafor)

# Study data
study <- c(${data.map(d => `"${String(d.study || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`).join(', ')})
`;

        // Add effect-specific data
        if (['HR', 'OR', 'RR'].includes(effectMeasure)) {
            code += `yi <- c(${data.map(d => d.effect.toFixed(6)).join(', ')})  # Log-transformed effects
sei <- c(${data.map(d => d.se.toFixed(6)).join(', ')})  # Standard errors
vi <- sei^2  # Variances

# Create data frame
dat <- data.frame(study = study, yi = yi, sei = sei, vi = vi)
`;
        } else if (effectMeasure === 'cstat') {
            code += `cstat <- c(${data.map(d => d.originalEffect.toFixed(4)).join(', ')})
se <- c(${data.map(d => d.originalSE?.toFixed(4) || 'NA').join(', ')})

# Logit transformation for C-statistic
yi <- log(cstat / (1 - cstat))
sei <- se / (cstat * (1 - cstat))
vi <- sei^2

dat <- data.frame(study = study, cstat = cstat, yi = yi, sei = sei, vi = vi)
`;
        } else {
            code += `yi <- c(${data.map(d => d.effect.toFixed(6)).join(', ')})
sei <- c(${data.map(d => d.se.toFixed(6)).join(', ')})
vi <- sei^2

dat <- data.frame(study = study, yi = yi, sei = sei, vi = vi)
`;
        }

        // Main meta-analysis
        const method = tau2Method === 'DL' ? 'DL' :
                       tau2Method === 'REML' ? 'REML' :
                       tau2Method === 'PM' ? 'PM' :
                       tau2Method === 'ML' ? 'ML' : 'REML';

        code += `
# Random-effects meta-analysis
res <- rma(yi = yi, vi = vi, data = dat, method = "${method}"${hksjAdjustment ? ', test = "knha"' : ''})

# Summary
summary(res)

# Forest plot
forest(res, slab = dat$study, xlab = "${getEffectLabel(effectMeasure)}",
       ${['HR', 'OR', 'RR'].includes(effectMeasure) ? 'atransf = exp,' : ''}
       header = "Study")
`;

        // Back-transformation for C-statistic
        if (effectMeasure === 'cstat') {
            code += `
# Back-transform to C-statistic scale
pooled_cstat <- plogis(res$beta)
ci_lower <- plogis(res$ci.lb)
ci_upper <- plogis(res$ci.ub)
cat("Pooled C-statistic:", round(pooled_cstat, 3),
    "[", round(ci_lower, 3), ",", round(ci_upper, 3), "]\\n")
`;
        }

        // Heterogeneity
        code += `
# Heterogeneity statistics
cat("\\nHeterogeneity:\\n")
cat("tau^2 =", round(res$tau2, 4), "\\n")
cat("I^2 =", round(res$I2, 1), "%\\n")
cat("H^2 =", round(res$H2, 2), "\\n")
cat("Q =", round(res$QE, 2), ", df =", res$k - 1, ", p =", round(res$QEp, 4), "\\n")
`;

        // Publication bias
        code += `
# Publication bias tests
# Funnel plot
funnel(res, xlab = "${getEffectLabel(effectMeasure)}")

# Egger's test
regtest(res)

# Trim and fill
tf <- trimfill(res)
summary(tf)
funnel(tf)

# Begg's test (rank correlation)
ranktest(res)
`;

        // Prediction interval
        code += `
# Prediction interval
predict(res)
`;

        // Subgroup analysis placeholder
        if (data.some(d => d.subgroup)) {
            code += `
# Subgroup analysis
dat$subgroup <- c(${data.map(d => d.subgroup ? `"${String(d.subgroup).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"` : 'NA').join(', ')})
res_sub <- rma(yi = yi, vi = vi, mods = ~ subgroup, data = dat, method = "${method}")
summary(res_sub)
`;
        }

        code += `
# Leave-one-out analysis
loo <- leave1out(res)
print(loo)

# Influence diagnostics
inf <- influence(res)
plot(inf)
`;

        return code;
    }

    /**
     * Generate Stata code
     */
    function generateStataCode(data, settings) {
        const { effectMeasure, tau2Method } = settings;

        let code = `* PrognosisMeta - Generated Stata Code
* Meta-analysis
* Generated: ${new Date().toISOString()}

* Clear and set up
clear all
set more off

* Input data
input str50 study yi sei
`;

        data.forEach(d => {
            // Escape quotes and newlines for Stata string syntax
            const escapedStudy = String(d.study || '').replace(/"/g, '""').replace(/[\n\r]/g, ' ');
            code += `"${escapedStudy}" ${d.effect.toFixed(6)} ${d.se.toFixed(6)}\n`;
        });

        code += `end

* Generate variance
gen vi = sei^2

* Random-effects meta-analysis
metan yi sei, random${tau2Method === 'REML' ? ' reml' : ''} ///
    label(namevar=study) ///
    effect(${getEffectLabel(effectMeasure)}) ///
    ${['HR', 'OR', 'RR'].includes(effectMeasure) ? 'eform' : ''} ///
    forestplot

* Heterogeneity (already reported by metan)

* Funnel plot
metafunnel yi sei, ///
    xtitle(${getEffectLabel(effectMeasure)}) ///
    ${['HR', 'OR', 'RR'].includes(effectMeasure) ? 'eform' : ''}

* Publication bias tests
* Egger's test
metabias yi sei, egger

* Begg's test
metabias yi sei, begg

* Trim and fill
metatrim yi sei

* Influence analysis
metainf yi sei, random
`;

        return code;
    }

    /**
     * Generate Python code
     */
    function generatePythonCode(data, settings) {
        const { effectMeasure, tau2Method } = settings;

        let code = `# PrognosisMeta - Generated Python Code
# Meta-analysis using statsmodels
# Generated: ${new Date().toISOString()}

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# Try to import optional packages
try:
    from statsmodels.stats.meta_analysis import CombineResults
    HAS_STATSMODELS = True
except ImportError:
    HAS_STATSMODELS = False
    print("statsmodels not available - using basic implementation")

# Study data
data = pd.DataFrame({
    'study': [${data.map(d => `'${String(d.study || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`).join(', ')}],
    'yi': [${data.map(d => d.effect.toFixed(6)).join(', ')}],
    'sei': [${data.map(d => d.se.toFixed(6)).join(', ')}]
})
data['vi'] = data['sei'] ** 2
data['wi'] = 1 / data['vi']

print("Study data:")
print(data)
print()

# Fixed-effect meta-analysis
w_sum = data['wi'].sum()
effect_fe = (data['wi'] * data['yi']).sum() / w_sum
se_fe = np.sqrt(1 / w_sum)
z_fe = effect_fe / se_fe
p_fe = 2 * (1 - stats.norm.cdf(abs(z_fe)))

print(f"Fixed-Effect Results:")
print(f"  Effect: {effect_fe:.4f}")
print(f"  SE: {se_fe:.4f}")
print(f"  95% CI: [{effect_fe - 1.96*se_fe:.4f}, {effect_fe + 1.96*se_fe:.4f}]")
print(f"  z = {z_fe:.2f}, p = {p_fe:.4f}")
print()

# Cochran's Q and I²
Q = ((data['wi'] * (data['yi'] - effect_fe)**2)).sum()
df = len(data) - 1
p_het = 1 - stats.chi2.cdf(Q, df)
C = w_sum - (data['wi']**2).sum() / w_sum
tau2 = max(0, (Q - df) / C)  # DerSimonian-Laird
I2 = max(0, 100 * (Q - df) / Q) if Q > df else 0

print(f"Heterogeneity:")
print(f"  Q = {Q:.2f}, df = {df}, p = {p_het:.4f}")
print(f"  tau² = {tau2:.4f}")
print(f"  I² = {I2:.1f}%")
print()

# Random-effects meta-analysis
data['wi_re'] = 1 / (data['vi'] + tau2)
w_sum_re = data['wi_re'].sum()
effect_re = (data['wi_re'] * data['yi']).sum() / w_sum_re
se_re = np.sqrt(1 / w_sum_re)
z_re = effect_re / se_re
p_re = 2 * (1 - stats.norm.cdf(abs(z_re)))

print(f"Random-Effects Results (DL):")
print(f"  Effect: {effect_re:.4f}")
print(f"  SE: {se_re:.4f}")
print(f"  95% CI: [{effect_re - 1.96*se_re:.4f}, {effect_re + 1.96*se_re:.4f}]")
print(f"  z = {z_re:.2f}, p = {p_re:.4f}")
`;

        if (['HR', 'OR', 'RR'].includes(effectMeasure)) {
            code += `
# Back-transform to original scale
effect_exp = np.exp(effect_re)
ci_lower = np.exp(effect_re - 1.96 * se_re)
ci_upper = np.exp(effect_re + 1.96 * se_re)
print(f"\\n${effectMeasure}: {effect_exp:.2f} [{ci_lower:.2f}, {ci_upper:.2f}]")
`;
        }

        code += `
# Prediction interval
k = len(data)
t_crit = stats.t.ppf(0.975, k - 2)
pi_var = 1/w_sum_re + tau2
pi_lower = effect_re - t_crit * np.sqrt(pi_var)
pi_upper = effect_re + t_crit * np.sqrt(pi_var)
print(f"\\n95% Prediction Interval: [{pi_lower:.4f}, {pi_upper:.4f}]")

# Forest plot
fig, ax = plt.subplots(figsize=(10, 6))

# Study points and CIs
y_pos = range(len(data))
for i, (_, row) in enumerate(data.iterrows()):
    lower = row['yi'] - 1.96 * row['sei']
    upper = row['yi'] + 1.96 * row['sei']
    ax.errorbar(row['yi'], i, xerr=[[row['yi'] - lower], [upper - row['yi']]],
                fmt='s', color='blue', capsize=3, markersize=np.sqrt(row['wi_re'] / w_sum_re) * 20)

# Pooled diamond
ax.fill([effect_re - 1.96*se_re, effect_re, effect_re + 1.96*se_re, effect_re],
        [len(data) + 0.5, len(data) + 0.8, len(data) + 0.5, len(data) + 0.2],
        color='red', alpha=0.7)

# Reference line
ax.axvline(x=0, color='gray', linestyle='--', alpha=0.5)

ax.set_yticks(list(y_pos) + [len(data) + 0.5])
ax.set_yticklabels(list(data['study']) + ['Pooled'])
ax.set_xlabel('Effect Size')
ax.set_title('Forest Plot')
plt.tight_layout()
plt.savefig('forest_plot.png', dpi=300)
plt.show()

# Funnel plot
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(data['yi'], data['sei'], s=50, alpha=0.7)
ax.axvline(x=effect_re, color='red', linestyle='-', label='Pooled effect')

# Pseudo 95% CI lines
max_se = data['sei'].max() * 1.1
se_range = np.linspace(0, max_se, 100)
ax.plot(effect_re - 1.96 * se_range, se_range, 'k--', alpha=0.5)
ax.plot(effect_re + 1.96 * se_range, se_range, 'k--', alpha=0.5)

ax.invert_yaxis()
ax.set_xlabel('Effect Size')
ax.set_ylabel('Standard Error')
ax.set_title('Funnel Plot')
plt.tight_layout()
plt.savefig('funnel_plot.png', dpi=300)
plt.show()

# Egger's test
precision = 1 / data['sei']
standardized = data['yi'] / data['sei']
slope, intercept, r_value, p_value, std_err = stats.linregress(precision, standardized)
print(f"\\nEgger's test:")
print(f"  Intercept = {intercept:.3f}")
print(f"  p-value = {p_value:.4f}")
`;

        return code;
    }

    // ============================================
    // Helper Functions
    // ============================================

    function formatEffect(effect, settings) {
        if (effect === undefined || effect === null || isNaN(effect) || !isFinite(effect)) return '--';

        const em = settings?.effectMeasure || 'HR';

        if (['HR', 'OR', 'RR'].includes(em)) {
            const exp = Math.exp(effect);
            return isFinite(exp) ? exp.toFixed(2) : '--';
        } else if (em === 'cstat') {
            return (1 / (1 + Math.exp(-effect))).toFixed(3);  // Inverse logit
        } else {
            return effect.toFixed(3);
        }
    }

    function formatCI(ci, settings) {
        if (!ci) return '[-- , --]';
        if (ci.lower === undefined || ci.upper === undefined) return '[-- , --]';
        if (!isFinite(ci.lower) || !isFinite(ci.upper)) return '[-- , --]';

        const em = settings?.effectMeasure || 'HR';

        if (['HR', 'OR', 'RR'].includes(em)) {
            return `[${Math.exp(ci.lower).toFixed(2)}, ${Math.exp(ci.upper).toFixed(2)}]`;
        } else if (em === 'cstat') {
            return `[${(1 / (1 + Math.exp(-ci.lower))).toFixed(3)}, ${(1 / (1 + Math.exp(-ci.upper))).toFixed(3)}]`;
        } else {
            return `[${ci.lower.toFixed(3)}, ${ci.upper.toFixed(3)}]`;
        }
    }

    function formatPValue(p) {
        if (p === undefined || p === null || isNaN(p)) return '= --';
        if (p < 0.001) return '< 0.001';
        return `= ${p.toFixed(3)}`;
    }

    function interpretI2(i2) {
        if (i2 === undefined || i2 === null) return '';
        if (i2 < 25) return 'Low heterogeneity';
        if (i2 < 50) return 'Moderate heterogeneity';
        if (i2 < 75) return 'Substantial heterogeneity';
        return 'Considerable heterogeneity';
    }

    function getEffectLabel(effectMeasure) {
        const labels = {
            'HR': 'Hazard Ratio',
            'OR': 'Odds Ratio',
            'RR': 'Risk Ratio',
            'beta': 'Coefficient',
            'cstat': 'C-statistic',
            'oe-ratio': 'O:E Ratio',
            'cal-slope': 'Calibration Slope',
            'cal-intercept': 'Calibration Intercept',
            'brier': 'Brier Score'
        };
        return labels[effectMeasure] || 'Effect Size';
    }

    // ============================================
    // PDF Generation
    // ============================================

    function generatePDF(htmlContent, filename = 'meta_analysis_report.pdf') {
        // Using jsPDF with html2canvas
        if (typeof jspdf === 'undefined' || typeof html2canvas === 'undefined') {
            console.error('jsPDF or html2canvas not loaded');
            return;
        }

        const { jsPDF } = jspdf;

        // Create temporary container
        const container = document.createElement('div');
        container.innerHTML = htmlContent;
        container.style.position = 'absolute';
        container.style.left = '-9999px';
        container.style.width = '8.5in';
        document.body.appendChild(container);

        html2canvas(container, {
            scale: 2,
            useCORS: true
        }).then(canvas => {
            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'in', 'letter');

            const imgWidth = 8.5;
            const pageHeight = 11;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;
            let heightLeft = imgHeight;
            let position = 0;

            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= pageHeight;

            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pageHeight;
            }

            pdf.save(filename);
            document.body.removeChild(container);
        });
    }

    // ============================================
    // Results Export
    // ============================================

    function exportResultsCSV(results, data, settings) {
        let csv = 'Meta-Analysis Results\n\n';

        csv += 'SUMMARY\n';
        csv += `Analysis Type,${settings.analysisType}\n`;
        csv += `Effect Measure,${settings.effectMeasure}\n`;
        csv += `Number of Studies,${data.length}\n`;
        csv += `Method,${results.method}\n\n`;

        csv += 'POOLED ESTIMATE\n';
        csv += `Effect,${formatEffect(results.effect, settings)}\n`;
        csv += `Lower CI,${formatEffect(results.ci?.lower, settings)}\n`;
        csv += `Upper CI,${formatEffect(results.ci?.upper, settings)}\n`;
        csv += `SE,${results.se?.toFixed(4)}\n`;
        csv += `z/t value,${(results.zValue || results.tValue)?.toFixed(2)}\n`;
        csv += `p-value,${results.pValue?.toFixed(4)}\n\n`;

        csv += 'HETEROGENEITY\n';
        csv += `Q,${results.Q?.toFixed(2)}\n`;
        csv += `df,${results.df}\n`;
        csv += `p (heterogeneity),${results.pHet?.toFixed(4)}\n`;
        csv += `I²,${results.I2?.toFixed(1)}%\n`;
        csv += `tau²,${results.tau2?.toFixed(4)}\n`;
        csv += `tau,${results.tau?.toFixed(4)}\n\n`;

        csv += 'STUDY DETAILS\n';
        csv += 'Study,N,Effect,SE,Lower CI,Upper CI,Weight (%)\n';
        data.forEach((study, i) => {
            // Escape quotes and guard against CSV formula injection
            let escapedStudy = String(study.study || '').replace(/"/g, '""');
            // Prefix with single quote if starts with formula characters
            if (/^[=+\-@\t\r]/.test(escapedStudy)) {
                escapedStudy = "'" + escapedStudy;
            }
            csv += `"${escapedStudy}",${study.n || ''},${formatEffect(study.effect, settings)},`;
            csv += `${study.se?.toFixed(4)},${formatEffect(study.effect - 1.96 * study.se, settings)},`;
            csv += `${formatEffect(study.effect + 1.96 * study.se, settings)},${results.weights?.[i]?.toFixed(1) || ''}\n`;
        });

        return csv;
    }


    // ============================================
    // Simple Export Functions (expected by tests)
    // ============================================

    /**
     * Export data to CSV format
     */
    function toCSV(data, options = {}) {
        if (!data) return '';

        const { delimiter = ',', includeHeaders = true } = options;
        let csv = '';

        // Handle array of objects
        if (Array.isArray(data)) {
            if (data.length === 0) return '';

            const keys = Object.keys(data[0]);
            if (includeHeaders) {
                csv += keys.join(delimiter) + '\n';
            }

            data.forEach(row => {
                csv += keys.map(key => {
                    let val = row[key];
                    if (val === null || val === undefined) return '';
                    let strVal = String(val);
                    // Guard against CSV formula injection
                    if (/^[=+\-@\t\r]/.test(strVal)) {
                        strVal = "'" + strVal;
                    }
                    if (strVal.includes(delimiter) || strVal.includes('"') || strVal.includes('\n')) {
                        return '"' + strVal.replace(/"/g, '""') + '"';
                    }
                    return strVal;
                }).join(delimiter) + '\n';
            });
        }
        // Handle single object
        else if (typeof data === 'object') {
            Object.entries(data).forEach(([key, value]) => {
                if (typeof value === 'object' && value !== null) {
                    csv += key + '\n';
                    csv += toCSV(Array.isArray(value) ? value : [value], options);
                } else {
                    csv += key + delimiter + String(value ?? '') + '\n';
                }
            });
        }

        return csv;
    }

    /**
     * Export data to JSON format
     */
    function toJSON(data, options = {}) {
        const { pretty = true, indent = 2 } = options;

        try {
            if (pretty) {
                return JSON.stringify(data, null, indent);
            }
            return JSON.stringify(data);
        } catch (e) {
            console.error('JSON export error:', e);
            return null;
        }
    }

    /**
     * Generate a complete analysis report
     */
    function generateReport(analysisData, format = 'html', options = {}) {
        switch (format.toLowerCase()) {
            case 'html':
                return generateHTMLReport(analysisData, options);
            case 'csv':
                return exportResultsCSV(
                    analysisData.results,
                    analysisData.data,
                    analysisData.settings
                );
            case 'json':
                return toJSON(analysisData, options);
            case 'r':
                return generateRCode(
                    analysisData.data,
                    analysisData.settings,
                    analysisData.results
                );
            case 'stata':
                return generateStataCode(
                    analysisData.data,
                    analysisData.settings
                );
            case 'python':
                return generatePythonCode(
                    analysisData.data,
                    analysisData.settings
                );
            default:
                return generateHTMLReport(analysisData, options);
        }
    }

    // ============================================
    // Public API
    // ============================================

    // Use enhanced code generators if available
    const useEnhanced = typeof CodeGenerators !== 'undefined';

    return {
        // Report generation
        generateHTMLReport,
        generatePDF,
        generateReport,

        // Code generation
        generateRCode: useEnhanced ? CodeGenerators.generateRCode : generateRCode,
        generateStataCode: useEnhanced ? CodeGenerators.generateStataCode : generateStataCode,
        generatePythonCode: useEnhanced ? CodeGenerators.generatePythonCode : generatePythonCode,

        // Data export
        exportResultsCSV,
        toCSV,
        toJSON,

        // Helpers
        formatEffect,
        formatCI,
        formatPValue,
        interpretI2
    };

})();

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ExportModule;
}
